"""Node registry for the DATA_SE_BATEN agent graph."""

from __future__ import annotations

from typing import Any, Callable, Dict

from agent.nodes.base import clear_store_cache, get_store, load_frame, ml_node, should_skip
from agent.nodes.pipeline_nodes import (
    algorithm_selection_node,
    anomaly_node,
    cleaning_node,
    deployment_node,
    eda_node,
    evaluation_node,
    explainability_node,
    feature_engineering_node,
    feedback_node,
    forecasting_node,
    ingest_node,
    monitoring_node,
    optimization_node,
    problem_detection_node,
    profiling_node,
    quality_gate_node,
    quality_node,
    reporting_node,
    split_node,
    training_node,
    unsupervised_node,
)
from agent.nodes.reasoning_nodes import (
    build_dataset_context,
    deterministic_answer,
    error_handler_node,
    narrative_node,
    planner_node,
    query_node,
)

#: node name -> callable used by the LangGraph builder
NODE_REGISTRY: Dict[str, Callable[[Dict[str, Any]], Dict[str, Any]]] = {
    "ingest": ingest_node,
    "planner": planner_node,
    "profile": profiling_node,
    "quality": quality_node,
    "clean": cleaning_node,
    "eda": eda_node,
    "detect": problem_detection_node,
    "select": algorithm_selection_node,
    "features": feature_engineering_node,
    "split": split_node,
    "train": training_node,
    "optimize": optimization_node,
    "evaluate": evaluation_node,
    "explain": explainability_node,
    "narrate": narrative_node,
    "gate": quality_gate_node,
    "unsupervised": unsupervised_node,
    "forecast": forecasting_node,
    "anomaly": anomaly_node,
    "report": reporting_node,
    "deploy": deployment_node,
    "monitor": monitoring_node,
    "feedback": feedback_node,
    "query": query_node,
    "error": error_handler_node,
}

__all__ = [
    "NODE_REGISTRY",
    "algorithm_selection_node",
    "anomaly_node",
    "build_dataset_context",
    "cleaning_node",
    "clear_store_cache",
    "deployment_node",
    "deterministic_answer",
    "eda_node",
    "error_handler_node",
    "evaluation_node",
    "explainability_node",
    "feature_engineering_node",
    "feedback_node",
    "forecasting_node",
    "get_store",
    "ingest_node",
    "load_frame",
    "ml_node",
    "monitoring_node",
    "narrative_node",
    "optimization_node",
    "planner_node",
    "problem_detection_node",
    "profiling_node",
    "quality_gate_node",
    "quality_node",
    "query_node",
    "reporting_node",
    "should_skip",
    "split_node",
    "training_node",
    "unsupervised_node",
]
